Update terraform_automation.yaml

diff --git a/.github/workflows/terraform_automation.yaml b/.github/workflows/terraform_automation.yaml
--- a/.github/workflows/terraform_automation.yaml
+++ b/.github/workflows/terraform_automation.yaml
@@ -7,7 +7,7 @@ on:
         description: 'The name of the organisation repository'
         required: true
         type: string
-      target-repo:
+      targetrepo:
         description: 'The name of the target repository for triggering workflows'
         required: true
         type: string
@@ -44,22 +44,22 @@ jobs:
       - name: Checkout app repo (app repo)
         uses: actions/checkout@v2
         with:
-          repository: ${{ github.event.inputs.orgname }}/${{ github.event.inputs.target-repo }}  # Use the target repository name from input
+          repository: ${{ github.event.inputs.orgname }}/${{ github.event.inputs.targetrepo }}  # Use the target repository name from input
           token: ${{ secrets.GIT_PAT }}  # Use Personal Access Token (PAT) if repository is private
-          path: ${{ github.event.inputs.target-repo }}  # Checkout app repo in a separate directory
+          path: ${{ github.event.inputs.targetrepo }}  # Checkout app repo in a separate directory
           ref: main  # Make sure the main branch is specified or change if needed
 
       - name: List files in the app repo's workflows directory
         run: |
           echo "Listing files in the app repo's workflows directory"
-          ls -R ${{ github.event.inputs.target-repo }}/.github/workflows || echo "Directory not found"
+          ls -R ${{ github.event.inputs.targetrepo }}/.github/workflows || echo "Directory not found"
 
       - name: Create .github/workflows directory in app repo if it doesn't exist
         run: |
           # Check if the .github/workflows directory exists in the app repo
-          if [ ! -d "${{ github.event.inputs.target-repo }}/.github/workflows" ]; then
+          if [ ! -d "${{ github.event.inputs.targetrepo }}/.github/workflows" ]; then
             echo "Directory .github/workflows does not exist. Creating directory."
-            mkdir -p ${{ github.event.inputs.target-repo }}/.github/workflows
+            mkdir -p ${{ github.event.inputs.targetrepo }}/.github/workflows
           else
             echo "Directory .github/workflows already exists."
           fi
@@ -79,13 +79,13 @@ jobs:
       - name: Copy ${{ github.event.inputs.template }}.yaml to app repo
         run: |
           echo "Copying ${{ github.event.inputs.template }}.yaml from automation repo to app repo."
-          cp .github/workflows/${{ github.event.inputs.template }}.yaml ${{ github.event.inputs.target-repo }}/.github/workflows/${{ github.event.inputs.template }}.yaml
+          cp .github/workflows/${{ github.event.inputs.template }}.yaml ${{ github.event.inputs.targetrepo }}/.github/workflows/${{ github.event.inputs.template }}.yaml
 
           # Check if there are any changes in the repo before committing
           git diff --exit-code || echo "Changes detected, committing."
 
           # Change directory to the app repo and commit changes if needed
-          cd ${{ github.event.inputs.target-repo }}
+          cd ${{ github.event.inputs.targetrepo }}
           git config --global user.email "naresh.reddivari@valuemomentum.com"
           git config --global user.name "nareshreddivari"
           git add .github/workflows/${{ github.event.inputs.template }}.yaml
@@ -101,7 +101,7 @@ jobs:
           # Trigger the workflow in the application repo
           echo "Triggering workflow in target application repo."
           curl -X POST \
-            https://api.github.com/repos/${{ github.event.inputs.org-name }}/${{ github.event.inputs.target-repo }}/actions/workflows/${{ github.event.inputs.template }}.yaml/dispatches \
+            https://api.github.com/repos/${{ github.event.inputs.org-name }}/${{ github.event.inputs.targetrepo }}/actions/workflows/${{ github.event.inputs.template }}.yaml/dispatches \
             -H "Accept: application/vnd.github.v3+json" \
             -H "Authorization: Bearer ${{ secrets.GIT_PAT }}" \
             -d '{"ref":"main","inputs":{"environment":"${{ github.event.inputs.environment }}","resource-type":"${{ github.event.inputs.resource-type }}"}}'
